[[section-technical-risks]]
== Risks and Technical Debts

In this page we are trying to show some of the problems we think that we will have to face during the system's develop and how we plan to solve or fix them.

=== Risks
* *SOLID*: It's a new world for us, we've never work with SOLID and we are not used to use it in our daily life, because it's a really new technology.
* *REACT JS*: We have a basic level of Javascript and this web framework use several concepts that we don't know very much, so it can bring to us some problems, like the REACT's components.
* *English*: It's not our native language so we find several difficulties to express some parts of the document, specifically, technical language, there might be some errors, our apologies for that.
* *NODE JS*: We will find some difficulties on managing node libraries, dependencies and asynchronous operations.
* *OPENSTREETMAP API*: We have previously worked with the Google Maps API, but never with OpenStreetMap API, so we will have certain difficulties and we will have to inform ourselves properly and read the documentation.
* *ARC42*: It's something new for us. Until now we had made the documentation in Word and subsequently generated a PDF, we had never used an arc42 template.
* *RDF AND LINKED DATA*: There aren’t much libraries to manage Linked Data, RDF resources and SPARQL. It is difficult to find them and use them, so we will have difficulties.

=== Measures to solve them

* According to the difficulties that English bring us, we are trying to use English dictionaries or online translators.
* We are trying to learn and search information on internet about SOLID, as much as possible, before starting code ViaDe application.
* We can take several online courses about NODE and REACT and using the well-known web page "Stackoverflow" to solve some individual doubts. Finally make our own REACT projects to know and get used to this new web framework.
* We can obtain sample code from different platforms ("Github", "Stackoverflow") to learn how to use the OPENSTREETMAP API, see how the different requests are made and the treatment of the data provided.
* We have been provided with a template in asciidoctor, that has helped us a lot to solve the problem. On the other hand, we are using asciidoctor, and we have been properly informed to be able to produce it, through Internet (tutorials, publications, etc.) and asking our teacher.
* To solve the difficulties with RDF and Linked data we have attended the SOLID talk (given by Empathy.co), that was held in the EII. They have provided us different tutorials and useful knowledge (e.g. libraries like ldflex or rdflib) to overcome them.
