[[section-technical-risks]]
== Risks and Technical Debts

In this page we are trying to show some of the problems we think that we will have to face during the system's develop and how we plan to solve or fix them.

=== Risks
* *SOLID*: it's a new world for us, we've never work with SOLID and we are not used to use it in our daily life, because it's a really new technology.
* *REACT JS*: we have a basic level of Javascript and this web framework use several concepts that we don't know very much, so it can bring to us some problems, like the REACT's components.
* *English*: it's not our native language so we find several difficulties to express some parts of the document, specifically, technical language, there might be some errors, our apologies for that.
* *NODE JS*: we will find some difficulties on managing node libraries, dependencies and asynchronous operations.

=== Measures to solve them

* According to the difficulties that English bring us, we are trying to use English dictionaries or online translators.
* We are trying to learn and search information on internet about SOLID, as much as possible, before starting code ViaDe application.
* We can take several online courses about NODE and REACT and using the well-known web page "Stackoverflow" to solve some individual doubts. Finally make our own REACT projects to know and get used to this new web framework.
