language: node_js
services: xvfb
node_js:
  - 12.14.0
cache:
  directories:
  - node_modules
warnings_are_errors: false
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ruby openjdk-8-jre
  - sudo gem install asciidoctor asciidoctor-diagram
script:
  - npm install -g codecov
  - npm test && codecov
  - CI=false npm run build
  - npm run docs
  - npm run test:e2e
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master
