version: '3'
services:
  solidserver:
    build: ./node-solid-server/
    volumes:
      - ./volumes/soliddata:/usr/src/app/data
      - ./volumes/soliddb:/usr/src/app/.db
    ports:
      - "8443:8443"
  es1c:
    build: .
    ports:
      - "3000:3000"
volumes:
  soliddata:
    external: false
  soliddb:
    external: false
